default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args:
          - --config
          - .markdownlint.yaml
          - --fix
        exclude: '^(CHANGELOG.md)$'

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.12
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: uv
        name: sync uv environment
        entry: uv sync
        language: system
        pass_filenames: false
        verbose: true
      - id: pytest
        name: run tests
        entry: uv run pytest pyresume/tests/
        language: system
        pass_filenames: false
        verbose: true
